### ISSUE TITLE
Is 5apps Quik Wik working?

### ISSUE THREAD

**Issue by theWebalyst** [maheee/QuikWik#4]
Hey, I'm probably just being dumb here but I'm trying https://quik-wik.5apps.com/

I'm not connecting to storage, but should I still be able to type into this?

I can resize, move the note window but can't see what else to do.

Thanks.

BTW my interest is in adding support to Quik Wik so it can be used on [SAFE Network](https://maidsafe.net), using a fork of RS.js

**Comment by maheee** [comment]
Hey,
in the top left corner of the note is the button to switch between source view (where you enter markdown) and the formatted view (which you are seeing).

And when you want to create more notes, just add links like this: `[qw](Other Note)`

I've never heard of the SAFE Network but that sounds interessting.

**Comment by theWebalyst** [comment]
Thanks - now how did I miss that?! I'll make it my next port to SAFE 😃 

I'll let you know when Quik Wik is working on SAFE network. SAFE is currently a closed alpha so if you want to play with it you will first need to join the [SAFE forum](https://safenetforum.org/) though and read a bit to get trust level 1 (basic user). 

Thanks for your help.
